In [ ]:
'''
../data/past_average_congestion_with_platform.csv
파일을 읽어와 dataframe으로 로드
'''
import pandas as pd



df = pd.read_csv('../../data/past_average_congestion_with_platform.csv')

df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,prevStationName,prevStationCode,congestionCar,getOffCarRate,next_station_congestion,totalCongestion,platformCongestion
0,2호선,삼성역,219,1,FRI,17,0,종합운동장역,218,"[31.0, 35.0, 35.0, 39.0, 40.0, 41.0, 51.0, 41....","[9.0, 10.0, 17.0, 12.0, 8.0, 7.0, 9.0, 9.0, 11...","[57.0, 52.0, 50.0, 56.0, 51.0, 58.0, 61.0, 61....","[57.0, 52.0, 50.0, 56.0, 51.0, 58.0, 61.0, 61....","[178.54, 127.13, 129.92, 134.45, 88.06, 123.22..."
1,2호선,삼성역,219,1,FRI,17,10,종합운동장역,218,"[46.6, 45.8, 49.4, 57.0, 44.8, 60.6, 54.0, 52....","[9.0, 9.0, 17.0, 11.2, 9.0, 6.2, 10.0, 9.0, 11...","[87.0, 71.0, 73.0, 82.0, 70.0, 75.0, 85.0, 68....","[87.0, 71.0, 73.0, 82.0, 70.0, 75.0, 85.0, 68....","[276.55, 181.84, 198.44, 194.63, 181.28, 112.6..."
2,2호선,삼성역,219,1,FRI,17,20,종합운동장역,218,"[52.4, 42.8, 55.4, 60.6, 61.8, 67.6, 69.0, 72....","[10.0, 10.8, 17.0, 10.0, 9.0, 6.0, 10.0, 9.0, ...","[80.6, 60.0, 75.4, 82.4, 78.6, 86.6, 84.6, 88....","[80.6, 60.0, 75.4, 82.4, 78.6, 86.6, 84.6, 88....","[207.38, 135.33, 182.44, 172.78, 138.68, 142.9..."
3,2호선,삼성역,219,1,FRI,17,30,종합운동장역,218,"[47.2, 56.2, 66.6, 63.6, 60.4, 69.8, 79.4, 67....","[10.2, 10.8, 17.0, 10.0, 9.0, 6.2, 9.0, 8.0, 1...","[67.0, 56.2, 68.2, 69.8, 57.4, 69.8, 77.0, 55....","[67.0, 56.2, 68.2, 69.8, 57.4, 69.8, 77.0, 55....","[152.65, 37.64, 80.14, 77.89, 15.11, 26.84, 29..."
4,2호선,삼성역,219,1,FRI,17,40,종합운동장역,218,"[37.4, 44.6, 47.8, 54.0, 47.8, 57.2, 53.0, 47....","[10.2, 10.8, 15.0, 11.0, 11.0, 7.0, 9.2, 8.0, ...","[57.0, 69.6, 70.6, 66.8, 68.6, 72.6, 77.4, 65....","[57.0, 69.6, 70.6, 66.8, 68.6, 72.6, 77.4, 65....","[145.21, 184.91, 185.86, 116.22, 161.6, 120.33..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,7호선,신풍역,743,1,WED,19,10,보라매역,742,"[62.125, 60.75, 64.875, 77.75, 59.375, 64.125,...","[8.875, 8.0, 8.875, 18.25, 14.125, 13.25, 13.8...","[55.125, 58.75, 60.75, 62.875, 55.125, 58.75, ...","[55.125, 58.75, 60.75, 62.875, 55.125, 58.75, ...","[0.0, 17.74, 10.12, 0.0, 25.65, 19.36, 0.0, 5.19]"
752,7호선,신풍역,743,1,WED,19,20,보라매역,742,"[55.375, 56.375, 55.375, 53.375, 54.375, 69.87...","[9.0, 7.875, 10.125, 17.125, 13.875, 13.5, 14....","[57.75, 60.125, 58.5, 56.75, 54.625, 68.125, 5...","[57.75, 60.125, 58.5, 56.75, 54.625, 68.125, 5...","[45.64, 50.79, 54.15, 77.62, 48.34, 47.65, 45...."
753,7호선,신풍역,743,1,WED,19,30,보라매역,742,"[42.375, 46.875, 45.125, 56.875, 41.5, 54.25, ...","[9.25, 8.25, 10.375, 18.125, 14.0, 13.0, 13.87...","[48.125, 51.0, 52.25, 60.375, 46.875, 60.25, 5...","[48.125, 51.0, 52.25, 60.375, 46.875, 60.25, 5...","[59.97, 49.56, 73.22, 85.63, 69.36, 80.95, 76...."
754,7호선,신풍역,743,1,WED,19,40,보라매역,742,"[35.875, 48.875, 40.875, 38.875, 40.625, 41.12...","[8.875, 9.75, 9.625, 18.875, 13.875, 13.875, 1...","[36.75, 51.5, 40.75, 38.0, 39.75, 41.625, 34.0...","[36.75, 51.5, 40.75, 38.0, 39.75, 41.625, 34.0...","[25.17, 45.83, 23.62, 40.08, 29.53, 38.49, 19...."
755,7호선,신풍역,743,1,WED,19,50,보라매역,742,"[36.5, 42.0, 39.75, 42.0, 43.75, 43.0, 36.5, 3...","[7.875, 9.75, 10.125, 19.75, 15.0, 12.375, 13....","[35.0, 39.5, 37.25, 39.375, 40.125, 40.75, 34....","[35.0, 39.5, 37.25, 39.375, 40.125, 40.75, 34....","[8.52, 9.89, 9.46, 35.16, 18.22, 19.05, 16.25,..."

In [2]:
'''
stationName, dow, hh, mm 순으로 정렬
'''
df = df.sort_values(by=['stationName', 'dow', 'hh', 'mm'])
df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,prevStationName,prevStationCode,congestionCar,getOffCarRate,next_station_congestion,totalCongestion,platformCongestion
378,7호선,대림역,744,1,FRI,17,0,신풍역,743,"[54.5, 45.75, 52.0, 50.625, 49.75, 52.625, 41....","[25.125, 16.0, 10.25, 9.0, 12.875, 13.125, 8.1...","[58.875, 58.0, 58.25, 59.875, 56.0, 58.875, 48...","[58.875, 58.0, 58.25, 59.875, 56.0, 58.875, 48...","[112.05, 121.36, 71.81, 85.62, 78.48, 81.59, 6..."
379,7호선,대림역,744,1,FRI,17,10,신풍역,743,"[50.25, 56.375, 50.125, 48.125, 51.125, 49.25,...","[26.875, 15.125, 10.25, 10.0, 11.875, 12.75, 7...","[61.75, 71.0, 66.0, 59.625, 59.75, 58.625, 51....","[61.75, 71.0, 66.0, 59.625, 59.75, 58.625, 51....","[155.07, 143.58, 130.31, 101.16, 91.14, 97.08,..."
380,7호선,대림역,744,1,FRI,17,20,신풍역,743,"[56.25, 56.25, 43.75, 51.5, 54.25, 53.5, 52.37...","[25.875, 16.0, 10.875, 9.125, 12.75, 12.125, 7...","[64.125, 67.0, 63.5, 64.125, 65.125, 57.0, 56....","[64.125, 67.0, 63.5, 64.125, 65.125, 57.0, 56....","[139.1, 122.48, 151.99, 107.44, 110.34, 61.93,..."
381,7호선,대림역,744,1,FRI,17,30,신풍역,743,"[65.875, 71.0, 66.875, 61.125, 67.125, 60.0, 6...","[23.875, 17.0, 10.875, 9.0, 12.125, 12.875, 7....","[71.5, 91.25, 86.375, 78.25, 81.25, 70.5, 81.2...","[71.5, 91.25, 86.375, 78.25, 81.25, 70.5, 81.2...","[132.42, 200.43, 166.03, 140.32, 138.07, 113.0..."
382,7호선,대림역,744,1,FRI,17,40,신풍역,743,"[62.0, 65.0, 63.0, 61.0, 65.0, 72.125, 59.875,...","[23.0, 17.125, 11.125, 9.125, 12.125, 12.0, 8....","[84.0, 82.0, 76.0, 82.0, 82.0, 88.0, 76.0, 63.0]","[84.0, 82.0, 76.0, 82.0, 82.0, 88.0, 76.0, 63.0]","[224.87, 174.46, 124.09, 164.75, 154.3, 152.12..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,2호선,역삼역,221,1,WED,19,10,선릉역,220,"[41.0, 41.6, 49.0, 48.8, 44.4, 51.6, 54.0, 44....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[42.2, 46.0, 56.2, 55.2, 49.0, 52.0, 58.0, 54....","[42.2, 46.0, 56.2, 55.2, 49.0, 52.0, 58.0, 54....","[20.16, 47.93, 78.08, 69.95, 58.82, 34.48, 61...."
374,2호선,역삼역,221,1,WED,19,20,선릉역,220,"[35.6, 48.6, 47.8, 55.6, 49.8, 52.4, 53.4, 46....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[46.8, 54.8, 60.0, 64.6, 59.0, 62.0, 67.4, 56....","[46.8, 54.8, 60.0, 64.6, 59.0, 62.0, 67.4, 56....","[80.5, 62.56, 108.27, 90.29, 91.03, 92.03, 123..."
375,2호선,역삼역,221,1,WED,19,30,선릉역,220,"[29.2, 38.4, 41.8, 39.4, 43.4, 40.8, 45.4, 37....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[36.2, 42.6, 46.4, 49.6, 44.8, 48.6, 52.8, 44....","[36.2, 42.6, 46.4, 49.6, 44.8, 48.6, 52.8, 44....","[52.47, 45.1, 57.04, 87.69, 38.29, 73.67, 76.8..."
376,2호선,역삼역,221,1,WED,19,40,선릉역,220,"[32.6, 37.6, 46.0, 46.0, 33.6, 38.8, 39.0, 37....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[32.8, 42.8, 53.6, 49.8, 42.6, 47.6, 47.2, 46....","[32.8, 42.8, 53.6, 49.8, 42.6, 47.6, 47.2, 46....","[11.35, 50.9, 78.51, 52.09, 78.73, 78.64, 77.4..."
377,2호선,역삼역,221,1,WED,19,50,선릉역,220,"[38.8, 38.8, 41.2, 42.0, 33.0, 41.2, 48.8, 27....","[5.0, 8.0, 11.0, 10.0, 11.0, 10.0, 11.0, 10.0,...","[43.0, 46.2, 49.4, 49.8, 37.6, 48.6, 55.0, 34....","[43.0, 46.2, 49.4, 49.8, 37.6, 48.6, 55.0, 34....","[38.08, 65.14, 78.96, 74.42, 51.04, 71.44, 71...."